image: docker:latest

build_job:
  stage: build
  script:
    - echo "Starting Docker Build"
    - docker build -t "${CI_PROJECT_NAME}:latest" .
    - echo "Job Finished. Sending notification to Discord"
    - curl -X POST https://cm.immortaldev.eu/api/stacks/webhooks/eadc21bb-b5e6-447f-97e7-5234474e53e3
  only:
    - release