image: docker:latest

build_job:
    stage: build
    script:
        - echo "Installing curl"
        - apk add --no-cache curl
        - echo "Starting Docker Build"
        - docker build -t "${CI_PROJECT_NAME}:latest" .
        - echo "Job Finished. Sending notification to Discord and triggering deployment."
        - curl -X POST https://docker01.immortaldev.eu/api/stacks/webhooks/59d41fe4-ad08-4195-808c-3c9650f64946
    only:
        - release
