image: docker:latest

build_job:
  stage: build
  script:
    - echo "Starting Docker Build"
    - docker build -t "${CI_PROJECT_NAME}:latest" .
    - echo "Job Finished. Sending notification to Discord"
  only:
    - release