image: docker:latest

build_job:
  stage: build
  script:
    - echo "Installing curl"
    - apk add --no-cache curl
    - echo "Starting Docker Build"
    - docker build -t "${CI_PROJECT_NAME}:latest" .
    - echo "Job Finished. Sending notification to Discord and triggering deployment"
    - curl -X POST https://cm.immortaldev.eu/api/stacks/webhooks/e3322129-4b0a-4eb4-aa94-0c470482209c
  only:
    - release
