image: docker:25

stages:
    - build
    - push
    - deploy

before_script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

Build:
    stage: build
    only:
        - release
    script:
        # fetches the latest image (not failing if image is not found)
        - docker pull $CI_REGISTRY_IMAGE:latest || true
        # builds the project, passing proxy variables, using OCI labels
        # notice the cache-from, which is going to use the image we just pulled locally
        # the built image is tagged locally with the commit SHA, and then pushed to
        # the GitLab registry
        - >
            docker build
            --pull
            --cache-from $CI_REGISTRY_IMAGE:latest
            --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
            --label "org.opencontainers.image.url=$CI_PROJECT_URL"
            --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
            --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
            --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
            --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
            .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

Push release:
    variables:
        GIT_STRATEGY: none
    stage: push
    only:
        - release
    script:
        - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
        - docker push $CI_REGISTRY_IMAGE:latest

Push tag:
    variables:
        GIT_STRATEGY: none
    stage: push
    only:
        - tags
    script:
        - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

Deploy Portainer:
    stage: deploy
    only:
        - release
    script:
        - apk update
        - apk add curl
        - curl -X POST https://cm1.immortaldev.eu/api/stacks/webhooks/cd4e71fc-3f08-40bb-8683-7320c8299bc0
