export enum ESearchType {
    IDENTIFIER = 'identifier',
    STEAMID = 'steamid',
    LICENSE = 'license',
    LIVEID = 'liveid',
    XBLID = 'xblid',
    DISCORD = 'discord',
    PLAYERIP = 'playerip',
    NAME = 'name',
    PLAYERNAME = 'playername',
    FIRSTNAME = 'firstname',
    LASTNAME = 'lastname',
    JOB = 'job',
    GROUP = 'group',
    PHONENUMBER = 'phonenumber',
    ALL = 'all',
}
